x-podman:
  in_pod: false
  
services:
  rutorrent:
    build: .
    container_name: rutorrent-monolith
    userns_mode: "keep-id:uid=1000,gid=1000"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/config:/config
      - ./volumes/downloads:/downloads
    environment:
      #AUTH_LEVEL: ALL # "ALL" or "WEBUI"
      #HTTP_USERNAME: test
      #HTTP_PASSWORD: test
    restart: unless-stopped