x-podman:
  in_pod: false

services:
  rutorrent:
    image: ggajus/rutorrent-monolith-rootless:local
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rutorrent-monolith
    userns_mode: "keep-id:uid=1000,gid=1000"
    network_mode: "pasta"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/config:/config
      - ./volumes/downloads:/downloads
    #environment:
      #AUTH_LEVEL: ALL # "ALL", "WEBUI" or "RPC2"
      #HTTP_USERNAME: test
      #HTTP_PASSWORD: test
    restart: unless-stopped
