[global]
error_log = /dev/stderr
log_level = warning

[www]
listen = /run/ops/php.sock
listen.owner = ops
listen.group = ops
listen.mode = 0660

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 2
pm.max_spare_servers = 5
pm.process_idle_timeout = 10s

clear_env = no
catch_workers_output = yes
decorate_workers_output = no